# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f69b6092a434967a1d665344e8352049c37a16a19e4bb56a0132b85ab7f6de2b3af7dd42b49d47cb1cc80c90795e6e6410abd71c77409db052a233a81e76d5c5

test:
  secret_key_base: fc791f4c47e3a6ae5dda34525e2fc1c0e2b9bc6e16546528557449c7a3b356a09aeddf04ff23e42d8db87f9757529dbc02b0b458947c624e73332cab9473f23e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
